### ISSUE TITLE
Clicking on Florida counties in social determinant map (Page 3) screwed up. 

### ISSUE THREAD

**Issue by olyerickson** [TheRensselaerIDEA/MortalityMinder#472]
Other states appear fine. Wrong counties highlighted for Florida.

**Comment by Random-W** [comment]
The bug is originated from a problem in the dataset.
Here is the two data frames we use for this plot:
![image](https://user-images.githubusercontent.com/33356939/69893371-7f89d300-12de-11ea-8572-1821296b8305.png)
![image](https://user-images.githubusercontent.com/33356939/69893376-97f9ed80-12de-11ea-8ab7-3162e5d53ca1.png)
We used "shapes" to do the actual plotting and dataset$county_name to do the labelling. However, for Florida, Okaloosa county is split into Okaloosa:main and Okaloosa:split in the dataset, causing discrepancies in shapes and labels. 

If there is no significant reason to justify why we split this county, I suggest that we should put them together.
