### ISSUE TITLE
Reactive "County Facts" for Louisiana throws error

### ISSUE THREAD

**Issue by olyerickson** [TheRensselaerIDEA/MortalityMinder#474]
Possible that county description is missing and we're not checking

**Comment by olyerickson** [comment]
Doesn't happen on all counties.

**Comment by RossDeVito** [comment]
The issue is counties not being in cdc.data. An example of this is La Salle, LA. This causes an issue in the County facts section as well as the Deaths of Despair Trends for Louisiana line plot on page two. I will update the County Facts section to say no data for x county when there is missing data, but I don't know how you want to handle the line plot issue. Optimally this would be solved by finding the missing data.
